#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

enum class SPELL_2DA
{
    Label = 0,
    Name,
    IconResRef,
    School,
    Range,
    VS,
    MetaMagic,
    TargetType,
    ImpactScript,
    Bard,
    Cleric,
    Druid,
    Paladin,
    Ranger,
    Wiz_Sorc,
    Innate,
    ConjTime,
    ConjAnim,
    ConjHeadVisual,
    ConjHandVisual,
    ConjGrndVisual,
    ConjSoundVFX,
    ConjSoundMale,
    ConjSoundFemale,
    CastAnim,
    CastTime,
    CastHeadVisual,
    CastHandVisual,
    CastGrndVisual,
    CastSound,
    Proj,
    ProjModel,
    ProjType,
    ProjSpwnPoint,
    ProjSound,
    ProjOrientation,
    ImmunityType,
    ItemImmunity,
    SubRadSpell1,
    SubRadSpell2,
    SubRadSpell3,
    SubRadSpell4,
    SubRadSpell5,
    Category,
    Master,
    UserType,
    Values,
    SpellDesc,
    UseConcentration,
    SpontaneouslyCast,
    AltMessage,
    HostileSetting,
    FeatID,
    Counter1,
    Counter2,
    HasProjectile
};

#endif